# Book settings
title : "Data Science in Practice"
author: Matthew Brett and Peter Rush
logo: images/dsfe_logo.png
email: matthew.brett@gmail.com
# >- starts a multiline string, where newlines replaced by spaces, and final
# newlines are stripped.
description: >-
  Textbook for London Interdisciplinary School Data Science in Practice module.

execute:
  # 'cache' attempts to cache the results.
  # 'auto' appears to be safer.
  execute_notebooks: cache
  timeout: 180

exclude_patterns:
  - README.md
  - todo.md
  - _scripts/*
  - _notes/*
  - bib/*
  - images/LICENSE.md
  - data/README.md
  - .pytest_cache/*
  - interactive-notebooks/*

html:
  favicon: images/dsfe_favicon.ico
  home_page_in_navbar: false
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  baseurl: https://odsti.github.io/dsip

repository:
  url: https://github.com/odsti/dsip
  branch: main

launch_buttons:
  # The interface interactive links will activate ["classic", "jupyterlab"]
  notebook_interface: "jupyterlab"
  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
  jupyterhub_url: "https://ds.lis.2i2c.cloud"
  # The URL of the BinderHub (e.g., https://mybinder.org)
  binderhub_url: "https://mybinder.org"
  # The URL of Google Colab (e.g., https://colab.research.google.com)
  # colab_url: "https://colab.research.google.com"
  thebe: true

sphinx:
  recursive_update: true
  config:
    # https://github.com/executablebooks/jupyter-book/issues/1950
    # Plotly mime type gives warning -> error.
    suppress_warnings: ["mystnb.unknown_mime_type"]
    html_theme_options:
      navigation_with_keys: false
    nb_custom_formats:
      .Rmd:
        - jupytext.reads
        - fmt: Rmd
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

  extra_extensions:
    # Needed as of 5 Dec 2022 - release of IPython 8.7.0
    # https://github.com/ipython/ipython/issues/13845
    # Fix from:
    # https://github.com/spatialaudio/nbsphinx/issues/24#issuecomment-267687633
    # Alternative is to pin install to !=8.7.0
    - IPython.sphinxext.ipython_console_highlighting

latex:
  latex_documents:
    targetname: dsip_textbook.tex

bibtex_bibfiles:
  - bib/course_refs.bib

# HTML redirection
# Pages linked, but then renamed.
redirection:
  builddir : _build/html
  redirects:
    # data-types/Ranges: ../arrays/Ranges
